# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://lawley.github.io/compress_to_ecl/"

git_url = "https://github.com/lawley/compress_to_ecl/tree/main/"

def custom_doc_links(name): return None
